<?php

namespace lpdw\SearchEngineBundle\Repository;

/**
 * FeatureValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureValueRepository extends \Doctrine\ORM\EntityRepository
{
}
